<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AppCliTools.CliParameters" Version="1.0.9686.36108" />
    <PackageVersion Include="AppCliTools.CliParametersDataEdit" Version="1.0.9686.36108" />
    <PackageVersion Include="AppCliTools.CliTools" Version="1.0.9686.36108" />
    <PackageVersion Include="AppCliTools.LibDataInput" Version="1.0.9686.36108" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
    <PackageVersion Include="ParametersManagement.LibApiClientParameters" Version="1.0.9686.34062" />
    <PackageVersion Include="ParametersManagement.LibDatabaseParameters" Version="1.0.9686.34062" />
    <PackageVersion Include="ParametersManagement.LibFileParameters" Version="1.0.9686.34062" />
    <PackageVersion Include="ParametersManagement.LibParameters" Version="1.0.9686.34062" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
    <PackageVersion Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8" />
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="SystemTools.SerilogStuff" Version="1.0.9686.33588" />
    <PackageVersion Include="SystemTools.SystemToolsShared" Version="1.0.9686.36920" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>