<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CrawlerConsoleData\CrawlerConsoleData.csproj" />
    <ProjectReference Include="..\SystemTools.DependencyInjection\SystemTools.DependencyInjection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ApiClientToolCommands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AppCliTools.CliParametersDataEdit" />
    <PackageReference Include="AppCliTools.CliTools" />
    <PackageReference Include="CrawlerServiceShared.Contracts" />
    <PackageReference Include="SystemTools.SerilogStuff" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
